#!/usr/bin/env bash
# Displays number from 1 to 100
# dislay fizz for 3, buzz for 5, fizzbuzz for 3 and 5

number=1

while [ $number -le 100 ]; do
	if (( $number % 3 == 0 )) && (( $number % 5 == 0 )); then
		echo "FizzBuzz"
	elif (( $number % 3 == 0 )); then
		echo "Fizz"
	elif (( $number % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$number"
	fi
	(( number++ ))
done
