#!/usr/bin/env bash
# display 4 and then "bad luck from China" for the 4th loop
# display 9 and then "bad luck from japan" for the 9th loop
# 17 and then "bad luck from Italy" for the 17th loop

count=1

while [ $count -le 20 ]; do
	echo "$count"
	case $count in
		4)
			echo "Bad luck from China"
			;;
		9)
			echo "Bad luck from Japan"
			;;
		17)
			echo "Bad luck from Italy"
			;;
	esac
	(( count++ ))
done
