#!/usr/bin/env bash
# Display hours from 0 to 12
# Display minutes from 1 to 59 of each hour.

hours=0
minutes=1

while [ $hours -le 12 ]; do
	echo "Hour: $hours"
	while [ $minutes -lt 60 ]; do
		echo "$minutes"
		(( minutes++ ))
	done
	minutes=1
	(( hours++ ))
done	       	
