#!/usr/bin/env bash
# Displays information about school.

if [ -e "school" ]; then
	echo "school file exists"
	if [ -s "school" ]; then
		echo "school is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]; then
		echo "school file is a regular file"
	fi
else
	echo "School file does not exist"
fi
